// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlyARMWs6h8ft3WTr1rTAiFcmVv7cxpD4',
    appId: '1:242979082480:web:bf4e35583bd288e4593235',
    messagingSenderId: '242979082480',
    projectId: 'vocabulary-7b44f',
    authDomain: 'vocabulary-7b44f.firebaseapp.com',
    storageBucket: 'vocabulary-7b44f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5E4fcG8XskKkWcwF3HmOuL3L13_EKXm8',
    appId: '1:242979082480:ios:50b1aa9ac2b7ef40593235',
    messagingSenderId: '242979082480',
    projectId: 'vocabulary-7b44f',
    storageBucket: 'vocabulary-7b44f.firebasestorage.app',
    iosBundleId: 'com.example.ra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5E4fcG8XskKkWcwF3HmOuL3L13_EKXm8',
    appId: '1:242979082480:ios:50b1aa9ac2b7ef40593235',
    messagingSenderId: '242979082480',
    projectId: 'vocabulary-7b44f',
    storageBucket: 'vocabulary-7b44f.firebasestorage.app',
    iosBundleId: 'com.example.ra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlyARMWs6h8ft3WTr1rTAiFcmVv7cxpD4',
    appId: '1:242979082480:web:19fbdcd6be9c30f8593235',
    messagingSenderId: '242979082480',
    projectId: 'vocabulary-7b44f',
    authDomain: 'vocabulary-7b44f.firebaseapp.com',
    storageBucket: 'vocabulary-7b44f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVX_oQUET4CmmpDm_OzI7P2fzWfFMBQuY',
    appId: '1:242979082480:android:094c204b2c4e1c2d593235',
    messagingSenderId: '242979082480',
    projectId: 'vocabulary-7b44f',
    storageBucket: 'vocabulary-7b44f.firebasestorage.app',
  );

}